language: go
go:
  - 1.8
  - 1.9
  - "1.10"
  - tip 

matrix:
  allow_failures:
    - go: master
  fast_finish: true

install: true

before_script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/) # All the .go files, excluding vendor/
  - go get github.com/mattn/goveralls

script:
  - go test -v -race ./...                   # Run all the tests with the race detector enabled
  - go vet ./...                             # go vet is the official Go static analyzer
  - $GOPATH/bin/goveralls -service=travis-ci # Run coverage analysis